name: expo

services:
  expo-service:
    image: klementevtech/expo:${EXPO_TAG:-latest}
    container_name: expo-service
    ports:
      - "${EXPO_PORT:-50051}:50051"
    volumes:
      - ./configs/config.toml:/etc/expo/config.toml:ro
    networks:
      - dev-network

  expo-k6:
    image: grafana/k6:latest
    container_name: expo-k6
    profiles:
      - perf
    volumes:
      - ./api/proto:/proto
      - ./test/k6:/scripts
    depends_on:
      - expo-service
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge