name: expo-compose

services:
  expo-service:
    image: klementevtech/expo:${VERSION:-latest}
    container_name: expo-service
    ports:
      - "50051:${GRPC_SERVER_PORT}"
    environment:
      GRPC_SERVER_HOST: ${GRPC_SERVER_HOST}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
    networks:
      - expo-network

  k6-test:
    image: grafana/k6:latest
    container_name: k6-test
    profiles:
      - k6-test
    volumes:
      - ./api/proto:/proto
      - ./test/k6:/scripts
    environment:
      GRPC_ADDRESS: expo-service:${GRPC_SERVER_PORT:-50051}
      VUS: ${VUS:-10}
      DURATION: ${DURATION:-30s}
    depends_on:
      - expo-service
    networks:
      - expo-network

networks:
  expo-network:
    driver: bridge