// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "expo/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPartRepository is a mock of PartRepository interface.
type MockPartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartRepositoryMockRecorder
	isgomock struct{}
}

// MockPartRepositoryMockRecorder is the mock recorder for MockPartRepository.
type MockPartRepositoryMockRecorder struct {
	mock *MockPartRepository
}

// NewMockPartRepository creates a new mock instance.
func NewMockPartRepository(ctrl *gomock.Controller) *MockPartRepository {
	mock := &MockPartRepository{ctrl: ctrl}
	mock.recorder = &MockPartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartRepository) EXPECT() *MockPartRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPartRepository) Create(ctx context.Context, part *model.Part) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, part)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPartRepositoryMockRecorder) Create(ctx, part any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPartRepository)(nil).Create), ctx, part)
}

// Delete mocks base method.
func (m *MockPartRepository) Delete(ctx context.Context, id model.PartID, oldVersion int64, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, oldVersion, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPartRepositoryMockRecorder) Delete(ctx, id, oldVersion, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPartRepository)(nil).Delete), ctx, id, oldVersion, deletedAt)
}

// Get mocks base method.
func (m *MockPartRepository) Get(ctx context.Context, id model.PartID) (*model.Part, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Part)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPartRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPartRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockPartRepository) List(ctx context.Context) ([]*model.Part, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*model.Part)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPartRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPartRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockPartRepository) Update(ctx context.Context, part *model.Part, oldVersion int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, part, oldVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPartRepositoryMockRecorder) Update(ctx, part, oldVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPartRepository)(nil).Update), ctx, part, oldVersion)
}
