// Code generated by MockGen. DO NOT EDIT.
// Source: expoapp/internal/handlers/expo (interfaces: VersionService)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/expo/mocks/version_service_mock.go -package=mocks expoapp/internal/handlers/expo VersionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "expoapp/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVersionService is a mock of VersionService interface.
type MockVersionService struct {
	ctrl     *gomock.Controller
	recorder *MockVersionServiceMockRecorder
	isgomock struct{}
}

// MockVersionServiceMockRecorder is the mock recorder for MockVersionService.
type MockVersionServiceMockRecorder struct {
	mock *MockVersionService
}

// NewMockVersionService creates a new mock instance.
func NewMockVersionService(ctrl *gomock.Controller) *MockVersionService {
	mock := &MockVersionService{ctrl: ctrl}
	mock.recorder = &MockVersionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionService) EXPECT() *MockVersionServiceMockRecorder {
	return m.recorder
}

// GetCurrentVersion mocks base method.
func (m *MockVersionService) GetCurrentVersion() *model.Version {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentVersion")
	ret0, _ := ret[0].(*model.Version)
	return ret0
}

// GetCurrentVersion indicates an expected call of GetCurrentVersion.
func (mr *MockVersionServiceMockRecorder) GetCurrentVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentVersion", reflect.TypeOf((*MockVersionService)(nil).GetCurrentVersion))
}
