// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: expo_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExpoService_GetInfoV1_FullMethodName = "/proto.ExpoService/GetInfoV1"
)

// ExpoServiceClient is the client API for ExpoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExpoServiceClient interface {
	GetInfoV1(ctx context.Context, in *GetInfoV1Request, opts ...grpc.CallOption) (*GetInfoV1Response, error)
}

type expoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExpoServiceClient(cc grpc.ClientConnInterface) ExpoServiceClient {
	return &expoServiceClient{cc}
}

func (c *expoServiceClient) GetInfoV1(ctx context.Context, in *GetInfoV1Request, opts ...grpc.CallOption) (*GetInfoV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoV1Response)
	err := c.cc.Invoke(ctx, ExpoService_GetInfoV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpoServiceServer is the server API for ExpoService service.
// All implementations must embed UnimplementedExpoServiceServer
// for forward compatibility.
type ExpoServiceServer interface {
	GetInfoV1(context.Context, *GetInfoV1Request) (*GetInfoV1Response, error)
	mustEmbedUnimplementedExpoServiceServer()
}

// UnimplementedExpoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExpoServiceServer struct{}

func (UnimplementedExpoServiceServer) GetInfoV1(context.Context, *GetInfoV1Request) (*GetInfoV1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfoV1 not implemented")
}
func (UnimplementedExpoServiceServer) mustEmbedUnimplementedExpoServiceServer() {}
func (UnimplementedExpoServiceServer) testEmbeddedByValue()                     {}

// UnsafeExpoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpoServiceServer will
// result in compilation errors.
type UnsafeExpoServiceServer interface {
	mustEmbedUnimplementedExpoServiceServer()
}

func RegisterExpoServiceServer(s grpc.ServiceRegistrar, srv ExpoServiceServer) {
	// If the following call panics, it indicates UnimplementedExpoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExpoService_ServiceDesc, srv)
}

func _ExpoService_GetInfoV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpoServiceServer).GetInfoV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpoService_GetInfoV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpoServiceServer).GetInfoV1(ctx, req.(*GetInfoV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ExpoService_ServiceDesc is the grpc.ServiceDesc for ExpoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExpoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ExpoService",
	HandlerType: (*ExpoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfoV1",
			Handler:    _ExpoService_GetInfoV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expo_service.proto",
}
