// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: expo_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoV1Request) Reset() {
	*x = GetInfoV1Request{}
	mi := &file_expo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoV1Request) ProtoMessage() {}

func (x *GetInfoV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_expo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoV1Request.ProtoReflect.Descriptor instead.
func (*GetInfoV1Request) Descriptor() ([]byte, []int) {
	return file_expo_service_proto_rawDescGZIP(), []int{0}
}

type GetInfoV1Response struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Version       *GetInfoV1Response_Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoV1Response) Reset() {
	*x = GetInfoV1Response{}
	mi := &file_expo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoV1Response) ProtoMessage() {}

func (x *GetInfoV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_expo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoV1Response.ProtoReflect.Descriptor instead.
func (*GetInfoV1Response) Descriptor() ([]byte, []int) {
	return file_expo_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoV1Response) GetVersion() *GetInfoV1Response_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetInfoV1Response_Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoV1Response_Version) Reset() {
	*x = GetInfoV1Response_Version{}
	mi := &file_expo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoV1Response_Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoV1Response_Version) ProtoMessage() {}

func (x *GetInfoV1Response_Version) ProtoReflect() protoreflect.Message {
	mi := &file_expo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoV1Response_Version.ProtoReflect.Descriptor instead.
func (*GetInfoV1Response_Version) Descriptor() ([]byte, []int) {
	return file_expo_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetInfoV1Response_Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_expo_service_proto protoreflect.FileDescriptor

const file_expo_service_proto_rawDesc = "" +
	"\n" +
	"\x12expo_service.proto\x12\x05proto\"\x12\n" +
	"\x10GetInfoV1Request\"t\n" +
	"\x11GetInfoV1Response\x12:\n" +
	"\aversion\x18\x01 \x01(\v2 .proto.GetInfoV1Response.VersionR\aversion\x1a#\n" +
	"\aVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2O\n" +
	"\vExpoService\x12@\n" +
	"\tGetInfoV1\x12\x17.proto.GetInfoV1Request\x1a\x18.proto.GetInfoV1Response\"\x00B\x14Z\x12expoapp/pkg/api/pbb\x06proto3"

var (
	file_expo_service_proto_rawDescOnce sync.Once
	file_expo_service_proto_rawDescData []byte
)

func file_expo_service_proto_rawDescGZIP() []byte {
	file_expo_service_proto_rawDescOnce.Do(func() {
		file_expo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expo_service_proto_rawDesc), len(file_expo_service_proto_rawDesc)))
	})
	return file_expo_service_proto_rawDescData
}

var file_expo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_expo_service_proto_goTypes = []any{
	(*GetInfoV1Request)(nil),          // 0: proto.GetInfoV1Request
	(*GetInfoV1Response)(nil),         // 1: proto.GetInfoV1Response
	(*GetInfoV1Response_Version)(nil), // 2: proto.GetInfoV1Response.Version
}
var file_expo_service_proto_depIdxs = []int32{
	2, // 0: proto.GetInfoV1Response.version:type_name -> proto.GetInfoV1Response.Version
	0, // 1: proto.ExpoService.GetInfoV1:input_type -> proto.GetInfoV1Request
	1, // 2: proto.ExpoService.GetInfoV1:output_type -> proto.GetInfoV1Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_expo_service_proto_init() }
func file_expo_service_proto_init() {
	if File_expo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expo_service_proto_rawDesc), len(file_expo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expo_service_proto_goTypes,
		DependencyIndexes: file_expo_service_proto_depIdxs,
		MessageInfos:      file_expo_service_proto_msgTypes,
	}.Build()
	File_expo_service_proto = out.File
	file_expo_service_proto_goTypes = nil
	file_expo_service_proto_depIdxs = nil
}
