// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: expo_service.proto

package expo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_expo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_expo_service_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_expo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_expo_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_expo_service_proto protoreflect.FileDescriptor

const file_expo_service_proto_rawDesc = "" +
	"\n" +
	"\x12expo_service.proto\x12\x04expo\"\x10\n" +
	"\x0eGetInfoRequest\"+\n" +
	"\x0fGetInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2G\n" +
	"\vExpoService\x128\n" +
	"\aGetInfo\x12\x14.expo.GetInfoRequest\x1a\x15.expo.GetInfoResponse\"\x00B\x16Z\x14expoapp/pkg/api/expob\x06proto3"

var (
	file_expo_service_proto_rawDescOnce sync.Once
	file_expo_service_proto_rawDescData []byte
)

func file_expo_service_proto_rawDescGZIP() []byte {
	file_expo_service_proto_rawDescOnce.Do(func() {
		file_expo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expo_service_proto_rawDesc), len(file_expo_service_proto_rawDesc)))
	})
	return file_expo_service_proto_rawDescData
}

var file_expo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_expo_service_proto_goTypes = []any{
	(*GetInfoRequest)(nil),  // 0: expo.GetInfoRequest
	(*GetInfoResponse)(nil), // 1: expo.GetInfoResponse
}
var file_expo_service_proto_depIdxs = []int32{
	0, // 0: expo.ExpoService.GetInfo:input_type -> expo.GetInfoRequest
	1, // 1: expo.ExpoService.GetInfo:output_type -> expo.GetInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_expo_service_proto_init() }
func file_expo_service_proto_init() {
	if File_expo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expo_service_proto_rawDesc), len(file_expo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expo_service_proto_goTypes,
		DependencyIndexes: file_expo_service_proto_depIdxs,
		MessageInfos:      file_expo_service_proto_msgTypes,
	}.Build()
	File_expo_service_proto = out.File
	file_expo_service_proto_goTypes = nil
	file_expo_service_proto_depIdxs = nil
}
