# config.toml

pprof_enabled = false

[log]
level = "info"

[grpc_server]
host = "0.0.0.0"
port = 50051

[rest_server]
host = "0.0.0.0"
port = 8080
read_header_timeout = "3s"

[pprof_server]
host = "0.0.0.0"
port = 6060
read_header_timeout = "3s"