// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cleanParts = `-- name: CleanParts :exec
DELETE FROM expo_parts
`

func (q *Queries) CleanParts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanParts)
	return err
}

const createPart = `-- name: CreatePart :exec
INSERT INTO expo_parts (id, name, version, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreatePartParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) error {
	_, err := q.db.ExecContext(ctx, createPart,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CreatedAt,
	)
	return err
}

const deletePart = `-- name: DeletePart :execresult
UPDATE expo_parts
SET version = version + 1,
    updated_at = ?1,
    deleted_at = ?2
WHERE id = ?3 AND version = ?4 AND deleted_at IS NULL
`

type DeletePartParams struct {
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	ID         uuid.UUID    `json:"id"`
	OldVersion int64        `json:"old_version"`
}

func (q *Queries) DeletePart(ctx context.Context, arg DeletePartParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePart,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
		arg.OldVersion,
	)
}

const existsPart = `-- name: ExistsPart :one
SELECT CAST(EXISTS(
    SELECT 1 FROM expo_parts
    WHERE id = ?1 AND deleted_at IS NULL
) AS BOOLEAN)
`

func (q *Queries) ExistsPart(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsPart, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getPart = `-- name: GetPart :one
SELECT id, name, version, created_at
FROM expo_parts
WHERE id = ?1 AND deleted_at IS NULL
LIMIT 1
`

type GetPartRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPart(ctx context.Context, id uuid.UUID) (GetPartRow, error) {
	row := q.db.QueryRowContext(ctx, getPart, id)
	var i GetPartRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listParts = `-- name: ListParts :many
SELECT id, name, version, created_at, updated_at
FROM expo_parts
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListPartsRow struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Version   int64        `json:"version"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ListParts(ctx context.Context) ([]ListPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsRow
	for rows.Next() {
		var i ListPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePart = `-- name: UpdatePart :execresult
UPDATE expo_parts
SET name = ?1,
    version = ?2,
    updated_at = ?3
WHERE id = ?4 AND version = ?5 AND deleted_at IS NULL
`

type UpdatePartParams struct {
	Name       string       `json:"name"`
	Version    int64        `json:"version"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	ID         uuid.UUID    `json:"id"`
	OldVersion int64        `json:"old_version"`
}

func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePart,
		arg.Name,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.OldVersion,
	)
}
