// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CleanParts(ctx context.Context) error
	CreatePart(ctx context.Context, arg CreatePartParams) error
	DeletePart(ctx context.Context, arg DeletePartParams) (sql.Result, error)
	ExistsPart(ctx context.Context, id uuid.UUID) (bool, error)
	GetPart(ctx context.Context, id uuid.UUID) (GetPartRow, error)
	ListParts(ctx context.Context) ([]ListPartsRow, error)
	UpdatePart(ctx context.Context, arg UpdatePartParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
