services:
  expo:
    image: klementevtech/expoapp:${VERSION:-latest}
    container_name: expo
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
    environment:
      GRPC_SERVER_HOST: ${GRPC_SERVER_HOST}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
    networks:
      - backend

networks:
  backend:
    driver: bridge

