// Code generated by MockGen. DO NOT EDIT.
// Source: expoapp/internal/web/expo (interfaces: VersionProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/web/expo/mocks/version_provider_mock.go -package=mocks expoapp/internal/web/expo VersionProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "expoapp/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVersionProvider is a mock of VersionProvider interface.
type MockVersionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockVersionProviderMockRecorder
	isgomock struct{}
}

// MockVersionProviderMockRecorder is the mock recorder for MockVersionProvider.
type MockVersionProviderMockRecorder struct {
	mock *MockVersionProvider
}

// NewMockVersionProvider creates a new mock instance.
func NewMockVersionProvider(ctrl *gomock.Controller) *MockVersionProvider {
	mock := &MockVersionProvider{ctrl: ctrl}
	mock.recorder = &MockVersionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionProvider) EXPECT() *MockVersionProviderMockRecorder {
	return m.recorder
}

// GetVersion mocks base method.
func (m *MockVersionProvider) GetVersion() *domain.Version {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(*domain.Version)
	return ret0
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockVersionProviderMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockVersionProvider)(nil).GetVersion))
}
